name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Nix store
      uses: actions/cache@v3
      id: nix-cache
      with:
        path: /tmp/nixcache
        key: nix-cache-${{ hashFiles('flake.nix') }}-${{ hashFiles('flake.lock') }}

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Import Nix store"
      if: "steps.nix-cache.outputs.cache-hit == 'true'"
      run: "nix-store --import < /tmp/nix-cache"

    - name: Build
      run: nix build --accept-flake-config

    - name: "Export Nix store"
      if: "steps.nix-cache.outputs.cache-hit == 'false'"
      run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nix-cache"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          result/lib/libauxcov.so
          result/lib/libauxtest.so
          result/lib/libdebug_server.so
